options:
  domain_name: "yerp"
  internal_interface: "em1"
  external_interface: "em0"
  internal_subnet: "10.10.10.0/24"
  internal_subnet_dhcp: "10.10.10.0"
  admin_ip: "10.10.10.2"
  internal_router: "10.10.10.1"
  gateway: "192.168.1.1"
  subnet: "10.10.1.0"
  subnet_mask: "255.255.255.0"
  dhcpd_range_low: "10.10.10.10"
  dhcpd_range_high: "10.10.10.250"
  dns_server_1: "8.8.8.8"
  dns_server_2: "4.2.2.1"
  sshd_interface: "em0"



config_pf:
  configs:
    - source: "config/pf.conf.template"
      destination: "/etc/pf.conf"
    - source: "config/dhcpd.conf.template"
      destination: "/etc/dhcpd.conf"
    - source: "config/hostname.em0.template"
      destination: "/etc/hostname.em0"
    - source: "config/hostname.em1.template"
      destination: "/etc/hostname.em1"
    - source: "config/rc.conf.local.template"
      destination: "/etc/rc.conf.local"
    - source: "config/sysctl.conf.template"
      destination: "/etc/sysctl.conf"

only_commands:
  commands:
    - "shutdown -r now"